<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>tardigrade_intro_control</name>
  <version>0.1.0</version>
  <description>Simulation-only Berkeley AUV controls onboarding project.</description>
  <maintainer email="software@berkeleyauv.org">Berkeley AUV</maintainer>
  <license>TODO</license>

  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>tardigrade_interfaces</depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
